version: '3.3'
services:
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in client.yaml"
    volumes:
      - ./data/client0:/app/data
      - ./client.yaml:/app/client.yaml
  client2:
    environment:
      - GET_HOSTS_FROM=dns
    image: "cifar-client:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in client.yaml"
    volumes:
      - ./data/client1:/app/data
      - ./client.yaml:/app/client.yaml

